### ISSUE TITLE
Time shows as "--:--:--" when v-model is set

### ISSUE THREAD

**Issue by nikkorejz** [MatijaNovosel/vue-material-time-picker#2]
Hi
When time picker hiding via `v-if`, for some reason actual time does not shows, although v-model is set to normal time in format like "HH:mm:ss"

![image](https://github.com/MatijaNovosel/vue-material-time-picker/assets/8490106/16c80d0e-4c4d-47d9-b6bd-ec399efa87a2)

**Comment by fry79** [comment]
Same problem.

**Comment by MatijaNovosel** [comment]
Should be fixed now, update the package to version `0.0.5`.
