### ISSUE TITLE
Allow to use custom header

### ISSUE THREAD

**Issue by nikkorejz** [MatijaNovosel/vue-material-time-picker#3]
Could you allow to use custom header or open functions to select hour/min/sec picker?

**Comment by MatijaNovosel** [comment]
Sure, I'll expose the hours, minutes and seconds individually so you can do whatever you want with them. Will update thread when done.

**Comment by MatijaNovosel** [comment]
Ok, update your package to version `0.0.6`. I've added a slot for the header - read the documentation [here](https://github.com/MatijaNovosel/vue-material-time-picker#header). I'm not sure if this is what you meant but I think it's close enough.
